[package]
name = "rustymicrobit"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.5"
panic-halt = "1.0.0"
mcp9808 = "0.4.0"
cortex-m = "0.7.7"
embedded-hal = "1.0.0"

[dependencies.stm32l4]
version = "0.15.1"
features = ["stm32l4r5"]